# Generated by Django 5.0 on 2024-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
